jobs:
  - job: rpix
    timeoutInMinutes: 360
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - checkout: self
        clean: true
      - script: ./run.sh
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: x-tools.tar.xz
          artifactName: ReleaseToolchain
