jobs:
  - job: rpix
    timeoutInMinutes: 360
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - checkout: self
        clean: true
      - script: ./run.sh
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'xtool'
          targetPath: '/home/vsts/x-tools'
